// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClOgYiOV-Ik98ldNfnKwUBKobm14Unp5o',
    appId: '1:510351600073:web:35cae0a8dcc35e8dada018',
    messagingSenderId: '510351600073',
    projectId: 'linkshelf-app-2026',
    authDomain: 'linkshelf-app-2026.firebaseapp.com',
    storageBucket: 'linkshelf-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAX48jl63K2AheHAwU738rdgqneHiGj_0',
    appId: '1:510351600073:android:8ac93782311577b5ada018',
    messagingSenderId: '510351600073',
    projectId: 'linkshelf-app-2026',
    storageBucket: 'linkshelf-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnmYbT62uDRBbW7ibfVfIYEnhN3XHaeiE',
    appId: '1:510351600073:ios:857b6b830de47b79ada018',
    messagingSenderId: '510351600073',
    projectId: 'linkshelf-app-2026',
    storageBucket: 'linkshelf-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.linkDecayApp',
  );
}
